export const apiOrders = [
  {
    id: 1,
    number: 'jdm83mx92m',
    createdAt: '2019-10-15T14:18:26',
    name: null,
    address: 'Calle Mayor, 12 1º D',
    postalCode: '03100',
    city: 'Alicante',
    province: 'Alicante',
    paymentMethod: 'VISA',
    shippingPrice: 5.5,
    products: [
      {
        id: 1,
        slug: 'test',
        name: 'Lorem ipsum plant one',
        image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/1.jpg',
        description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
        longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
        discount: 10,
        isNew: true,
        rating: 5,
        price: 10.6,
        amount: 2
      }
    ]
  },
  {
    id: 2,
    number: 'kfync623d3',
    createdAt: '2019-11-02T11:48:46',
    name: 'Jose Manuel Deltell Lopez',
    address: 'Calle Mayor, 12 1º D',
    postalCode: '03100',
    city: 'Elda',
    province: 'Alicante',
    paymentMethod: 'VISA',
    shippingPrice: 5.5,
    products: [
      {
        id: 3,
        slug: 'lorem-ipsum-plant-three',
        name: 'Lorem ipsum plant three',
        image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/3.jpg',
        description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
        longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
        discount: 30,
        isNew: false,
        rating: 4,
        price: 14.5,
        amount: 3
      },
      {
        id: 8,
        slug: 'lorem-ipsum-plant-eight',
        name: 'Lorem ipsum plant eight',
        image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/8.jpg',
        description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
        longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
        discount: 10,
        isNew: true,
        rating: 4,
        price: 32.5,
        amount: 1
      },
    ]
  },
  {
    id: 3,
    number: '4jfn58f091',
    createdAt: '2020-03-02T23:58:01',
    name: 'Evaristo Perez Campos',
    address: 'Calle Altamira, 123 8º B',
    postalCode: '03113',
    city: 'Guadalajara',
    province: 'Guadalajara',
    paymentMethod: 'MASTERCARD',
    shippingPrice: 5.5,
    products: [
      {
        id: 16,
        slug: 'lorem-ipsum-plant-sixteen',
        name: 'Lorem ipsum plant sixteen',
        image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/6.jpg',
        description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
        longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
        discount: 0,
        isNew: true,
        rating: 5,
        price: 10.6,
        amount: 2
      },
    ]
  },
  {
    id: 4,
    number: '384ngzxsde',
    createdAt: '2021-01-21T21:28:06',
    name: 'Laura Alted Perez',
    address: 'Calle Lopez, 23 3º A',
    postalCode: '03001',
    city: 'Madrid',
    province: 'Madrid',
    paymentMethod: 'PAYPAL',
    shippingPrice: 5.5,
    products: [
      {
        id: 17,
        slug: 'lorem-ipsum-plant-seventeen',
        name: 'Lorem ipsum plant seventeen',
        image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/7.jpg',
        description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
        longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
        discount: 10,
        isNew: false,
        rating: 2,
        price: 10.6,
        amount: 1
      },
    ]
  },
  {
    id: 5,
    number: '384jfn45n1',
    createdAt: '2021-02-21T21:28:06',
    name: 'Laura Alted Perez',
    address: 'Calle Lopez, 23 3º A',
    postalCode: '03001',
    city: 'Tarrassa',
    province: 'Barcelona',
    paymentMethod: 'STRIPE',
    shippingPrice: 5.5,
    products: [
      {
        id: 17,
        slug: 'lorem-ipsum-plant-seventeen',
        name: 'Lorem ipsum plant seventeen',
        image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/7.jpg',
        description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
        longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
        discount: 10,
        isNew: false,
        rating: 2,
        price: 10.6,
        amount: 1
      },
    ]
  },
  {
    id: 6,
    number: '12jnfi459a',
    createdAt: '2021-05-21T21:28:06',
    name: 'Laura Alted Perez',
    address: 'Calle Lopez, 23 3º A',
    postalCode: '03001',
    city: 'Móstoles',
    province: 'Madrid',
    paymentMethod: 'VISA',
    shippingPrice: 5.5,
    products: [
      {
        id: 17,
        slug: 'lorem-ipsum-plant-seventeen',
        name: 'Lorem ipsum plant seventeen',
        image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/7.jpg',
        description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
        longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
        discount: 10,
        isNew: false,
        rating: 2,
        price: 10.6,
        amount: 1
      },
    ]
  },
  {
    id: 7,
    number: '0eh3b183nc',
    createdAt: '2021-11-21T21:28:06',
    name: 'Laura Alted Perez',
    address: 'Calle Lopez, 23 3º A',
    postalCode: '03001',
    city: 'Novelda',
    province: 'Alicante',
    paymentMethod: 'VISA',
    shippingPrice: 5.5,
    products: [
      {
        id: 17,
        slug: 'lorem-ipsum-plant-seventeen',
        name: 'Lorem ipsum plant seventeen',
        image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/7.jpg',
        description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
        longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
        additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
        discount: 10,
        isNew: false,
        rating: 2,
        price: 10.6,
        amount: 1
      },
    ]
  }
]