export const apiProducts = [
  {
    id: 1,
    slug: 'test',
    name: 'Lorem ipsum plant one',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/1.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 10,
    isNew: true,
    rating: 5,
    price: 10.6
  },
  {
    id: 2,
    slug: 'lorem-ipsum-plant-two',
    name: 'Lorem ipsum plant two',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/2.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 10,
    isNew: true,
    rating: 5,
    price: 22.5
  },
  {
    id: 3,
    slug: 'lorem-ipsum-plant-three',
    name: 'Lorem ipsum plant three',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/3.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 30,
    isNew: false,
    rating: 4,
    price: 14.5
  },
  { id: 4,
    slug: 'lorem-ipsum-plant-four',
    name: 'Lorem ipsum plant four',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/4.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 0,
    isNew: false,
    rating: 4,
    price: 15.6
  },
  { id: 5,
    slug: 'lorem-ipsum-plant-five',
    name: 'Lorem ipsum plant five',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/5.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 20,
    isNew: true,
    rating: 3,
    price: 12.5
  },
  { id: 6,
    slug: 'lorem-ipsum-plant-six',
    name: 'Lorem ipsum plant six',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/6.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 20,
    isNew: true,
    rating: 5,
    price: 22.5
  },
  { id: 7,
    slug: 'lorem-ipsum-plant-seven',
    name: 'Lorem ipsum plant seven',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/7.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 0,
    isNew: false,
    rating: 4,
    price: 12.5
  },
  { id: 8,
    slug: 'lorem-ipsum-plant-eight',
    name: 'Lorem ipsum plant eight',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/8.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 10,
    isNew: true,
    rating: 4,
    price: 32.5
  },
  { id: 9,
    slug: 'lorem-ipsum-plant-nine',
    name: 'Lorem ipsum plant nine',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/1.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 10,
    isNew: false,
    rating: 5,
    price: 10.6
  },
  { id: 10,
    slug: 'lorem-ipsum-plant-ten',
    name: 'Lorem ipsum plant ten',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/2.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 0,
    isNew: true,
    rating: 1,
    price: 10.6
  },
  { id: 11,
    slug: 'lorem-ipsum-plant-eleven',
    name: 'Lorem ipsum plant eleven',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/1.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 0,
    isNew: false,
    rating: 0,
    price: 10.6
  },
  { id: 12,
    slug: 'lorem-ipsum-plant-twelve',
    name: 'Lorem ipsum plant twelve',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/2.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 0,
    isNew: false,
    rating: 0,
    price: 10.6
  },
  { id: 13,
    slug: 'lorem-ipsum-plant-thirteen',
    name: 'Lorem ipsum plant thirteen',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/3.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 0,
    isNew: false,
    rating: 2,
    price: 10.6
  },
  { id: 14,
    slug: 'lorem-ipsum-plant-fourteen',
    name: 'Lorem ipsum plant fourteen',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/4.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 50,
    isNew: false,
    rating: 5,
    price: 10.6
  },
  { id: 15,
    slug: 'lorem-ipsum-plant-fifteen',
    name: 'Lorem ipsum plant fifteen',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/5.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 20,
    isNew: false,
    rating: 4,
    price: 10.6
  },
  { id: 16,
    slug: 'lorem-ipsum-plant-sixteen',
    name: 'Lorem ipsum plant sixteen',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/6.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 0,
    isNew: true,
    rating: 5,
    price: 10.6
  },
  { id: 17,
    slug: 'lorem-ipsum-plant-seventeen',
    name: 'Lorem ipsum plant seventeen',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/7.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 10,
    isNew: false,
    rating: 2,
    price: 10.6
  },
  { id: 18,
    slug: 'lorem-ipsum-plant-eighteen',
    name: 'Lorem ipsum plant eighteen',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/8.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 0,
    isNew: false,
    rating: 3,
    price: 10.6
  },
  { id: 19,
    slug: 'lorem-ipsum-plant-nineteen',
    name: 'Lorem ipsum plant nineteen',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/1.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 0,
    isNew: false,
    rating: 2,
    price: 10.6
  },
  { id: 20,
    slug: 'lorem-ipsum-plant-twenty',
    name: 'Lorem ipsum plant twenty',
    image: 'https://flone.jamstacktemplates.dev/assets/img/product/plants/2.jpg',
    description: 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
    longDescription: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
    additionalInfo: '<ul><li><span>Weight</span> 400 g</li><li><span>Dimensions</span>10 x 10 x 15 cm </li><li><span>Materials</span> 60% cotton, 40% polyester</li><li><span>Other Info</span> American heirloom jean shorts pug seitan letterpress</li></ul>',
    discount: 0,
    isNew: false,
    rating: 1,
    price: 10.6
  }
]